const questions = [
	"Hey",
	"Hi",
	"Tell me a Joke",
	"How are you ?",
	"Hola how are you?",
	"Thank you",
	"Shit",
	"I need cheering up",
	"You are very intelligent",
	"Can you prove you are self-aware",
	"Shut up",
	"Are you gonna destroy Humanity?",
	"Should I be worried about AI?",
	"Tell me some gossip",
	"How a water pump works?",
	"How much are the harry potter movies worth?",
	"How a rocket engine works?",
	"How old was sue lyon when she made lolita?",
	"How bruce lee died?",
	"How did Anne Frank died?",
	"How are antibodies used in?",
	"How much is 7 teaspoons?",
	"How cds are read?",
	"How deep is the atlantic ocean?",
	"How old was shakespeare's juliet?",
	"How did Bob Marley die?",
	"How much is a ream of paper?",
	"How much is a yen coin?",
	"How an oil rig works?",
	"How much is an adult film actor paid?",
	"How deadly are brain tumors?",
	"How are sheep slaughtered?",
	"What did isaac newton do?",
	"What color is hazel?",
	"How does a cell function?",
	"How many bones are in the skeletal system?",
	"What freezes faster? hot or cold water?",
	"How many countries are member of the eu?",
	"Shut the fuck up in Spanish",
	"What episode do they play the second opening in Death note?",
	"How old is XP operating system?",
	"How many pawns in chess?",
	"How is hydrogen produced?",
	"How LCD Monitors Work",
	"What can a guinea pig do for a human?",
	"How much calcium is in salt water?",
	"When is halley's comet comming next?",
	"What are shrooms the drug?",
	"What are D.O. of medicine?",
	"Who played batman in dark knight?",
	"What is a millionth of a meter?",
	"What makes a dwarf planet?",
	"What are debit cards made of?",
	"What is a monarch to a monarchy?",
	"Who designed the statue of liberty?",
	"Who invented the thermometer?",
	"What are leaf lobe?",
	"What type of land is savannah?",
	"Who did james bond work for?",
	"What are the top three laws in science?",
	"What are DAT files?",
	"Who made the roller skates?",
	"When was pearl harbor bombed?",
	"What religion is primary in africa?",
	"What versions of windows do not have powershell?",
	"Who invented the television?",
	"What to see in malaysia?",
	"What are stocks and bonds?",
	"What is a neuro tract?",
	"What temperature is a salt ice bath?",
	"What are the 7 continents?",
	"What is a vm server?",
	"What Is Argentina Known For?",
	"What is diet pepsi flavored with?",
	"Where is the Real Mona Lise located?",
	"Where is dora from?",
	"When was Apple Computer founded?"
];

const randomQuestion = () => {
	return questions[Math.floor(Math.random() * questions.length)];
};

export default randomQuestion;
